-- Run in the Supabase SQL editor. RLS deliberately defaults to deny.
create extension if not exists pgcrypto;
create type public.user_role as enum ('admin');
create type public.inquiry_status as enum ('new','pending','replied','confirmed','closed','spam');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, role public.user_role not null default 'admin', created_at timestamptz not null default now());
create table public.rooms (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, description text not null default '', daily_price_lkr integer not null check(daily_price_lkr >= 0), monthly_price_lkr integer not null check(monthly_price_lkr >= 0), published boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.room_facilities (id uuid primary key default gen_random_uuid(), room_id uuid not null references public.rooms(id) on delete cascade, label text not null, position smallint not null default 0, unique(room_id,label));
create table public.gallery_images (id uuid primary key default gen_random_uuid(), storage_path text unique not null, alt_text text not null, published boolean not null default false, position smallint not null default 0, created_at timestamptz not null default now());
create table public.booking_inquiries (id uuid primary key default gen_random_uuid(), guest_name text not null, email text not null, phone text not null, room_slug text, guests smallint not null check(guests > 0 and guests <= 12), check_in date not null, check_out date not null check(check_out > check_in), message text not null default '', status public.inquiry_status not null default 'new', internal_notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index booking_inquiries_status_created_idx on public.booking_inquiries(status,created_at desc); create index booking_inquiries_dates_idx on public.booking_inquiries(check_in,check_out);
create table public.reviews (id uuid primary key default gen_random_uuid(), guest_name text not null, body text not null, stay_date date, published boolean not null default false, verified_at timestamptz, created_at timestamptz not null default now());
create table public.availability (id uuid primary key default gen_random_uuid(), room_id uuid not null references public.rooms(id) on delete cascade, start_date date not null, end_date date not null check(end_date > start_date), status text not null check(status in ('blocked','reserved')), created_at timestamptz not null default now()); create index availability_room_dates_idx on public.availability(room_id,start_date,end_date);
create table public.site_settings (key text primary key, value jsonb not null, public boolean not null default false, updated_at timestamptz not null default now());
create table public.management_actions (id uuid primary key default gen_random_uuid(), actor_id uuid references auth.users(id), action text not null, entity_type text not null, entity_id uuid, created_at timestamptz not null default now());
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin')$$;
alter table public.profiles enable row level security; alter table public.rooms enable row level security; alter table public.room_facilities enable row level security; alter table public.gallery_images enable row level security; alter table public.booking_inquiries enable row level security; alter table public.reviews enable row level security; alter table public.availability enable row level security; alter table public.site_settings enable row level security; alter table public.management_actions enable row level security;
create policy "published rooms are public" on public.rooms for select using(published); create policy "admins manage rooms" on public.rooms for all using(public.is_admin()) with check(public.is_admin());
create policy "facilities follow published room" on public.room_facilities for select using(exists(select 1 from public.rooms r where r.id=room_id and r.published)); create policy "admins manage facilities" on public.room_facilities for all using(public.is_admin()) with check(public.is_admin());
create policy "published gallery is public" on public.gallery_images for select using(published); create policy "admins manage gallery" on public.gallery_images for all using(public.is_admin()) with check(public.is_admin());
create policy "published verified reviews are public" on public.reviews for select using(published and verified_at is not null); create policy "admins manage reviews" on public.reviews for all using(public.is_admin()) with check(public.is_admin());
create policy "public settings readable" on public.site_settings for select using(public); create policy "admins manage settings" on public.site_settings for all using(public.is_admin()) with check(public.is_admin());
create policy "admins manage inquiries" on public.booking_inquiries for all using(public.is_admin()) with check(public.is_admin()); create policy "admins manage availability" on public.availability for all using(public.is_admin()) with check(public.is_admin()); create policy "admins view profiles" on public.profiles for select using(public.is_admin()); create policy "admins manage actions" on public.management_actions for all using(public.is_admin()) with check(public.is_admin());
-- The inquiry API uses a server-only service-role client after strict edge validation; do not add an anonymous SELECT policy.
