import { notFound } from "next/navigation"; import Link from "next/link";
const content:Record<string,{title:string;eyebrow:string;body:string}>= {
 experience:{eyebrow:"The pace of your stay",title:"Make space for a quieter day.",body:"Spend time on the balcony, return to green surroundings after the coast, and experience Habaraduwa at a more local pace. The homestay is about seven minutes inland from Habaraduwa Beach."},
 gallery:{eyebrow:"Property gallery",title:"A home for the photographs to come.",body:"No property images were supplied with this project, so this gallery intentionally does not substitute stock imagery. Add verified property photographs through the admin gallery before publishing this page."},
 food:{eyebrow:"Food on request",title:"Sri Lankan curries from Amma’s kitchen.",body:"Authentic homemade Sri Lankan curries may be available on request. Please contact the family in advance to ask what can be prepared for your stay."},
 location:{eyebrow:"Habaraduwa, Southern Sri Lanka",title:"Near the coast, in a calmer setting.",body:"The accommodation is within a family home in Habaraduwa, approximately seven minutes inland from Habaraduwa Beach. Contact the family for exact arrival guidance after your inquiry is confirmed."},
 reviews:{eyebrow:"Guest reviews",title:"Only genuine guest voices belong here.",body:"No verified guest reviews were supplied, so none are displayed. Reviews can be published from the admin dashboard only after they have been verified."},
 faq:{eyebrow:"Helpful details",title:"Questions before you inquire?",body:"Availability is confirmed directly by the family. Rates are listed per day and per month. Homemade curries may be available on request. Personal laundry is available for the Bigger Double Room on request at Rs. 200–500/kg."},
 privacy:{eyebrow:"Privacy",title:"How inquiry information is handled.",body:"We collect the contact and stay details you submit so the family can respond to your inquiry. Inquiry data is not published. It is stored privately and should only be accessed by authorised homestay administrators. Contact us to request access, correction or deletion where applicable."},
 terms:{eyebrow:"Terms",title:"A clear, inquiry-first stay.",body:"Submitting an inquiry does not create a booking or guarantee availability. The family confirms dates, room details and any requested arrangements directly. Prices shown are subject to confirmation by the family before a stay is agreed."},
 guides:{eyebrow:"Local guides",title:"Local notes will be shared here.",body:"This future section is intentionally empty until the family has genuine local guidance to publish."},
 offers:{eyebrow:"Offers",title:"No offers are currently published.",body:"Check directly with the family for confirmed dates and prices."},
 availability:{eyebrow:"Availability",title:"Ask the family about dates.",body:"Live availability is not displayed until it is managed from the database. Send an inquiry and the family will confirm directly."}
};
export function generateStaticParams(){return Object.keys(content).map(page=>({page}));}
export default async function Info({params}:{params:Promise<{page:string}>}){const {page}=await params;const c=content[page];if(!c)notFound();return <section className="shell py-14"><p className="eyebrow">{c.eyebrow}</p><h1 className="display mt-3 max-w-3xl text-5xl">{c.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-ink/75">{c.body}</p>{!["privacy","terms","gallery","reviews","guides"].includes(page)&&<Link href="/contact" className="mt-8 inline-block rounded-full bg-leaf px-5 py-3 font-bold text-white">Send an inquiry</Link>}</section>}
